### ISSUE TITLE
app启动时闪退

### ISSUE THREAD

**Issue by xiaxc1** [VenusCao/x5_webview_flutter#20]
我在run 时候  控制台输出如下
Launching lib\main.dart on BND AL10 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Application finished.

app进入程序就闪退了

**Comment by xiaxc1** [comment]
下载的这个案例  还没有改动就打不开  安卓9

**Comment by VenusCao** [comment]
请参阅注意事项的两种解决方法

**Comment by VenusCao** [comment]
使用0.2.0版本
