### ISSUE TITLE
Can you guys please also provide English Translation?

### ISSUE THREAD

**Issue by Omi231** [VenusCao/x5_webview_flutter#24]
Hi,

This plugin seems interesting to me. Would you guys please provide a documentation in english also so that everyone can understand?

Thanks

**Comment by VenusCao** [comment]
Sorry, because the X5 kernel does not support internationalization temporarily, it cannot be used in countries other than China.

[Official documents](https://x5.tencent.com/tbs/technical.html#/detail/sdk/1/14e9f3f4-ed64-4330-8e31-25d1f1a68cf7)
