### ISSUE TITLE
android 6.0以上权限BUG

### ISSUE THREAD

**Issue by eveinzz** [VenusCao/x5_webview_flutter#26]
### 环境
android版本：10
权限情况：已授权文件读写

### 问题：初始化X5出错
我对X5内核进行初始化加载：
`X5Sdk.init().then((isOK) {
        print(isOK ? "X5内核成功加载" : "X5内核加载失败");
      });`
在这里报错，一直无法初始化成功：
> W/FileUtils( 7567): Failed to chmod(/data/user/0/com.tencent.mm/app_tbs): android.system.ErrnoException: chmod failed: EACCES (Permission denied)
W/FileUtils( 7567): Failed to chmod(/data/user/0/com.tencent.mobileqq/app_tbs): android.system.ErrnoException: chmod failed: EACCES (Permission denied)
W/FileUtils( 7567): Failed to chmod(/data/user/0/com.tencent.mm/app_tbs): android.system.ErrnoException: chmod failed: EACCES (Permission denied)
W/FileUtils( 7567): Failed to chmod(/data/user/0/com.tencent.mobileqq/app_tbs): android.system.ErrnoException: chmod failed: EACCES (Permission denied)

说无权，但我已经授权了文件读写权限，并进行了二次权限校验。

### android 6.0之上的系统除了添加权限还要在你报错的代码前面添加请求权限的代码
我在[stackoverflow](https://stackoverflow.com/questions/23527767/open-failed-eacces-permission-denied)中得知，在 android 6以上系统虽然已经授权了，但在使用权限时还得需要再次请求权限，所以出现了上面的错误。

解决方法，上面stackoverflow中已经给出了解决方案，能否请G主确认一下是否是这个问题，并修复更新，感谢！

### 补充一
发现本包使用的SDK（`v4.3.0.1148_43697`）只支持32位，但官方的最新版X5SDK（`v4.3.0.3_43903`）已经支持64位。老大抽时间更新一下吧。
````
64位手机无法加载x5(libmttwebview.so is 32-bit instead of 64-bit)
新版本SDK已支持64位，请更新至官网最新43903版本SDK
````
[link](https://x5.tencent.com/tbs/technical.html#/detail/sdk/1/34cf1488-7dc2-41ca-a77f-0014112bcab7)

### 补充二
目前使用X5内核的核心用途是用来播放视频，但是经测试使用`X5Sdk.openVideo`打开的视频，只要暂停再播放就闪退（内存泄露），老大是否有计划修复呢？

如果用`openWebActivity`来播放视频的话就推动意义了，不知如果升级官网最新43903版本SDK是否能解决这个BUG呢？

**Comment by VenusCao** [comment]
谢谢你的意见
权限可以自己去申请 [permission_handler](https://pub.flutter-io.cn/packages/permission_handler)
sdk已更新，请使用0.2.0
X5Sdk.openVideo的问题，screenMode 传102，104就不会闪退了，这个是需要官方处理的。

**Comment by eveinzz** [comment]
> 谢谢你的意见
> 权限可以自己去申请 [permission_handler](https://pub.flutter-io.cn/packages/permission_handler)
> sdk已更新，请使用0.2.0
> X5Sdk.openVideo的问题，screenMode 传102，104就不会闪退了，这个是需要官方处理的。

收到，权限问题我就是使用permission_handler申请的，是申请同意了，然后一直出现无权的错误，所以才发的此贴，目前没找到解决方案。感谢更新SDK，点赞！

**Comment by VenusCao** [comment]
示例代码等几天更新。

 ```
void loadX5() async {
    //请求动态权限，6.0安卓及以上必有
    Map<Permission, PermissionStatus> statuses = await [
      Permission.phone,
      Permission.storage,
    ].request();
    //判断权限
    if (!(statuses[Permission.phone].isGranted &&
        statuses[Permission.storage].isGranted)) {
      showDialog(
          context: context,
          builder: (context) {
            return AlertDialog(
              content: Text("请同意所有权限后再尝试加载X5"),
              actions: [
                FlatButton(
                    onPressed: () {
                      Navigator.pop(context);
                    },
                    child: Text("取消")),
                FlatButton(
                    onPressed: () {
                      Navigator.pop(context);
                      loadX5();
                    },
                    child: Text("再次加载")),
                FlatButton(
                    onPressed: () {
                      Navigator.pop(context);
                      openAppSettings();
                    },
                    child: Text("打开设置页面")),
              ],
            );
          });
      return;
    }

    //没有x5内核，是否在非wifi模式下载内核。默认false
    await X5Sdk.setDownloadWithoutWifi(true);

    //内核下载安装监听
    await X5Sdk.setX5SdkListener(X5SdkListener(onInstallFinish: () {
      print("X5内核安装完成");
    }, onDownloadFinish: () {
      print("X5内核下载完成");
    }, onDownloadProgress: (int progress) {
      print("X5内核下载中---$progress%");
    }));
    print("----开始加载内核----");
    var isOk = await X5Sdk.init();
    print(isOk ? "X5内核成功加载" : "X5内核加载失败");
  }
```

**Comment by eveinzz** [comment]
收到，感谢～～
