### ISSUE TITLE
DEMO显示下载失败，X5内核未启动

### ISSUE THREAD

**Issue by aiwenzx007** [VenusCao/x5_webview_flutter#3]
引用最新的0.1.2使用示例代码同样提示下载失败

**Comment by VenusCao** [comment]
是用的真机测试吗？你点击demo的X5内核信息里面倒数第二个看看提示什么？最好能上图

**Comment by aiwenzx007** [comment]
点第二个没有任何提示，无反映。是不是安卓9.0的问题？跳转腾讯的TBS调试地址同样报下载失败

**Comment by VenusCao** [comment]
什么机型？

**Comment by aiwenzx007** [comment]
华为荣耀10，安卓版本9.0




------------------ 原始邮件 ------------------
发件人: "VenusCao"<notifications@github.com>; 
发送时间: 2019年6月20日(星期四) 中午11:32
收件人: "VenusCao/x5_webview_flutter"<x5_webview_flutter@noreply.github.com>; 
抄送: "半根烟"<1288424@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [VenusCao/x5_webview_flutter] DEMO显示下载失败，X5内核未启动 (#3)




什么机型？

**Comment by VenusCao** [comment]
添加这一行试试android:usesCleartextTraffic="true"
```
<application
        ...
        android:usesCleartextTraffic="true"
       >
</application>
```

**Comment by aiwenzx007** [comment]
这个问题解决了，但是64位的NDK配置上就闪屏退出

**Comment by VenusCao** [comment]
可以选择用android sdk运行

**Comment by aiwenzx007** [comment]
我用AS运行提示couldn't find "libflutter.so

**Comment by VenusCao** [comment]
使用AS打开android目录下的build.gradle,使用新窗口运行
如果还是不行，你可以使用Terminal运行：
```
flutter build apk --debug --target-platform=android-arm
flutter run --use-application-binary=build/app/outputs/apk/debug/app-debug.apk
```
详情见：https://github.com/flutter/flutter/pull/34369

**Comment by aiwenzx007** [comment]
使用终端运行搞定，谢谢
