### ISSUE TITLE
Android 5.1.1 横屏时播放器被上一个flutter页面覆盖

### ISSUE THREAD

**Issue by jackxuechen** [VenusCao/x5_webview_flutter#32]
![BBEA94DE-3D88-428A-93BE-F66C46A0DFA3](https://user-images.githubusercontent.com/10265395/103185605-149f3700-48f8-11eb-9ac8-33006a3cdbea.png)
![20211228105127](https://user-images.githubusercontent.com/10265395/103186225-af007a00-48fa-11eb-91f7-dbb34b57df7d.jpg)

**Comment by jackxuechen** [comment]
flutter页面内部嵌套X5WebView

**Comment by VenusCao** [comment]
内嵌有兼容问题的话，请使用openWebActivity或自己定义android原生Activity来处理
