### ISSUE TITLE
这个网址打不开 你可以在你的demo里面试试

### ISSUE THREAD

**Issue by mimicode** [VenusCao/x5_webview_flutter#33]
https://m.you.163.com/?channel_type=1_11111110&from=out_cps_duomai_0

**Comment by VenusCao** [comment]
请自行处理网址重定向和多次跳转的问题

**Comment by mimicode** [comment]
> 请自行处理网址重定向和多次跳转的问题

能给个例子吗？没看到能获取或者控制重定向的 方法

**Comment by VenusCao** [comment]
onUrlLoading: (url) {}
