### ISSUE TITLE
x5_webview_flutter能否设置循环播放当前视频

### ISSUE THREAD

**Issue by patton88** [VenusCao/x5_webview_flutter#35]
x5_webview_flutter效果很不错，不知能否设置自动开始播放、循环播放当前视频，如果能够增加这些简单功能，就更强大了，先行谢过！

HTML 5 视频是支持自动开始播放、循环播放功能的：
https://www.w3school.com.cn/html5/html_5_video.asp

属性 | 值 | 描述
-- | -- | --
autoplay | autoplay | 如果出现该属性，则视频在就绪后马上播放。
controls | controls | 如果出现该属性，则向用户显示控件，比如播放按钮。
height | pixels | 设置视频播放器的高度。
loop | loop | 如果出现该属性，则当媒介文件完成播放后再次开始播放。
preload | preload | 如果出现该属性，则视频在页面加载时进行加载，并预备播放。如果使用 "autoplay"，则忽略该属性。
src | url | 要播放的视频的 URL。
width | pixels | 设置视频播放器的宽度。

**Comment by VenusCao** [comment]
如果是内嵌webview可以自行处理下，openvideo的话腾讯那边没提供相关api
