### ISSUE TITLE
内嵌的时候出现这个问题

### ISSUE THREAD

**Issue by CLZ666** [VenusCao/x5_webview_flutter#36]
内嵌的时候出现这个问题
The getter 'names' was called on null.
Receiver: null
Tried calling: names
The relevant error-causing widget was: 
  X5WebView file:/lib/pages/WebPage.dart:85:19
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      _CreationParams.fromWidget (package:x5_webview/x5_webview.dart:246:55)
#2      _X5WebViewState.build.<anonymous closure> (package:x5_webview/x5_webview.dart:82:45)
#3      _PlatformViewLinkState._initialize (package:flutter/src/widgets/platform_view.dart:878:47)
#4      _PlatformViewLinkState.initState (package:flutter/src/widgets/platform_view.dart:856:5)

**Comment by VenusCao** [comment]
加上这个，忘记判断空了
```
     X5WebView(
        ...
        javascriptChannels: JavascriptChannels(
            ["X5Web", "Toast"], (name, data) {
          switch (name) {
            ...
          }
        }))
```
