### ISSUE TITLE
JavascriptChannel 接受不到js页面postmessage的回调

### ISSUE THREAD

**Issue by maonickbob** [VenusCao/x5_webview_flutter#37]
`X5WebView(
           url: "file:///android_asset/flutter_assets/webview/index.html",
           javaScriptEnabled: true,
           javascriptChannels: JavascriptChannels(["test"], (name, data) {
             print("333333333333333333");
             AppSettings.openWIFISettings();
             switch (name) {
               default:
                 print("5");
                 break;
             }
           }),`
页面正常打开，js的postmessage能正常执行，只是flutter这边接收不到回调，我换了个插件是可以正确执行的，不知道哪里出了问题

**Comment by VenusCao** [comment]
请对比example里面demo.dart通信方式
