### ISSUE TITLE
如何与打开的html页面交互

### ISSUE THREAD

**Issue by catalsdevelop** [VenusCao/x5_webview_flutter#4]
比如传递和接收数据，只能在onPageFinished事件里面执行脚本么？有没有类似postMessage的方式。

**Comment by VenusCao** [comment]
暂不支持 js调用flutter

**Comment by VenusCao** [comment]
postMessage的话，你直接写一个function返回需要的数据，然后使用evaluateJavascript来获取就可以了

**Comment by VenusCao** [comment]
下个版本会增加js调flutter

**Comment by catalsdevelop** [comment]
感谢，希望尽快支持js调用flutter

**Comment by VenusCao** [comment]
0.1.3版本增加了
