### ISSUE TITLE
网页中包含一个视频，点击视频的全屏按钮时无响应，然后整个页面卡死，页面无响应

### ISSUE THREAD

**Issue by wangfeng211** [VenusCao/x5_webview_flutter#45]
控制台输出以下内容：

D/SurfaceUtils(31770): connecting to surface 0xb400007b5462f010, reason connectToSurface
I/MediaCodec(31770): [OMX.qcom.video.decoder.avc] setting surface generation to 32532494
D/SurfaceUtils(31770): disconnecting from surface 0xb400007b5462f010, reason connectToSurface(reconnect)
D/SurfaceUtils(31770): connecting to surface 0xb400007b5462f010, reason connectToSurface(reconnect)
D/SurfaceUtils(31770): set up nativeWindow 0xb400007b5462f010 for 640x368, color 0x7fa30c06, rotation 0, usage 0x20402900
D/SurfaceUtils(31770): disconnecting from surface 0xb400007b81f75010, reason disconnectFromSurface
E/Surface (31770): freeAllBuffers: 45 buffers were freed while being dequeued!
D/SurfaceUtils(31770): disconnecting from surface 0xb400007b5462f010, reason disconnectFromSurface

测试环境：Redmi K40，Android12

**Comment by VenusCao** [comment]
内嵌还是openWebActivity

**Comment by wangfeng211** [comment]
内嵌

**Comment by VenusCao** [comment]
试试0.4.0 如还有问题从新打开
