### ISSUE TITLE
内嵌浏览爱奇艺网站视频时候点击视频全屏崩溃

### ISSUE THREAD

**Issue by aiwenzx007** [VenusCao/x5_webview_flutter#9]
附上报错日志
I/PlayerBase(11541): isRestricted: falseLeftvolume: 1.0 Rightvolume: 1.0mPanMultiplierL: 1.0mPanMultiplierR: 1.0
D/HiTouch_PressGestureDetector(11541): HiTouch on notch display, width corret:90
I/HiTouch_HiTouchSensor(11541): ORIENTATION_LANDSCAPE
D/HwAppInnerBoostImpl(11541): asyncReportData com.bst.bst_life_app,1,1,5,0 interval=2341
W/libEGL  (11541): EGLNativeWindowType 0xd0bdc008 disconnect failed
D/mali_winsys(11541): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
W/libEGL  (11541): EGLNativeWindowType 0xd0bdc808 disconnect failed
D/mali_winsys(11541): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
E/SurfaceView(11541): Exception configuring surface
E/SurfaceView(11541): java.lang.NullPointerException: Attempt to read from field 'android.view.Surface android.view.ViewRootImpl.mSurface' on a null object reference
E/SurfaceView(11541):   at android.view.SurfaceView.applySurfaceTransforms(SurfaceView.java:900)
E/SurfaceView(11541):   at android.view.SurfaceView.setParentSpaceRectangle(SurfaceView.java:918)
E/SurfaceView(11541):   at android.view.SurfaceView.surfacePositionLost_uiRtSync(SurfaceView.java:1026)
W/libEGL  (11541): EGLNativeWindowType 0xd0bdc008 disconnect failed
D/mali_winsys(11541): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/HwAppInnerBoostImpl(11541): asyncReportData com.bst.bst_life_app,1,2,1,3 interval=2379
I/ViewRootImpl(11541): jank_removeInvalidNode all the node in jank list is out of time
W/InputMethodManager(11541): startInputReason = 4
W/System.err(11541): java.lang.AbstractMethodError: abstract method "boolean com.tencent.smtt.export.external.extension.interfaces.IX5WebViewExtension.isX5CoreSandboxMode()"
W/System.err(11541):    at com.tencent.smtt.sdk.WebView.a(Unknown Source:95)
W/System.err(11541):    at com.tencent.smtt.sdk.WebView.onDetachedFromWindow(Unknown Source:27)
W/System.err(11541):    at android.view.View.dispatchDetachedFromWindow(View.java:18628)
W/System.err(11541):    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3831)
W/System.err(11541):    at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:5638)
W/System.err(11541):    at android.view.ViewGroup.removeAllViews(ViewGroup.java:5584)
W/System.err(11541):    at io.flutter.plugin.platform.SingleViewPresentation.detachState(SingleViewPresentation.java:155)
W/System.err(11541):    at io.flutter.plugin.platform.VirtualDisplayController.resize(VirtualDisplayController.java:83)
W/System.err(11541):    at io.flutter.plugin.platform.PlatformViewsController.resizePlatformView(PlatformViewsController.java:264)
W/System.err(11541):    at io.flutter.plugin.platform.PlatformViewsController.onMethodCall(PlatformViewsController.java:148)
W/System.err(11541):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
W/System.err(11541):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
W/System.err(11541):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
W/System.err(11541):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(11541):    at android.os.MessageQueue.next(MessageQueue.java:386)
W/System.err(11541):    at android.os.Looper.loop(Looper.java:169)
W/System.err(11541):    at android.app.ActivityThread.main(ActivityThread.java:7470)
W/System.err(11541):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(11541):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
W/System.err(11541):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
W/System.err(11541): java.lang.SecurityException: getDeviceId
W/System.err(11541):    at android.os.Parcel.createException(Parcel.java:1953)
W/System.err(11541):    at android.os.Parcel.readException(Parcel.java:1921)
W/System.err(11541):    at android.os.Parcel.readException(Parcel.java:1871)
W/System.err(11541):    at com.android.internal.telephony.IHwTelephony$Stub$Proxy.getUniqueDeviceId(IHwTelephony.java:2028)
W/System.err(11541):    at android.telephony.HwTelephonyManagerInner.getUniqueDeviceId(HwTelephonyManagerInner.java:1096)
W/System.err(11541):    at android.telephony.HwInnerTelephonyManagerImpl.getUniqueDeviceId(HwInnerTelephonyManagerImpl.java:351)
W/System.err(11541):    at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:1264)
W/System.err(11541):    at com.tencent.smtt.utils.b.c(Unknown Source:21)
W/System.err(11541):    at com.tencent.smtt.sdk.a.b.a(Unknown Source:209)
W/System.err(11541):    at com.tencent.smtt.sdk.WebView.a(Unknown Source:116)
W/System.err(11541):    at com.tencent.smtt.sdk.WebView.onDetachedFromWindow(Unknown Source:27)
W/System.err(11541):    at android.view.View.dispatchDetachedFromWindow(View.java:18628)
W/System.err(11541):    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3831)
W/System.err(11541):    at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:5638)
W/System.err(11541):    at android.view.ViewGroup.removeAllViews(ViewGroup.java:5584)
W/System.err(11541):    at io.flutter.plugin.platform.SingleViewPresentation.detachState(SingleViewPresentation.java:155)
W/System.err(11541):    at io.flutter.plugin.platform.VirtualDisplayController.resize(VirtualDisplayController.java:83)
W/System.err(11541):    at io.flutter.plugin.platform.PlatformViewsController.resizePlatformView(PlatformViewsController.java:264)
W/System.err(11541):    at io.flutter.plugin.platform.PlatformViewsController.onMethodCall(PlatformViewsController.java:148)
W/System.err(11541):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
W/System.err(11541):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
W/System.err(11541):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
W/System.err(11541):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(11541):    at android.os.MessageQueue.next(MessageQueue.java:386)
W/System.err(11541):    at android.os.Looper.loop(Looper.java:169)
W/System.err(11541):    at android.app.ActivityThread.main(ActivityThread.java:7470)
W/System.err(11541):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(11541):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
W/System.err(11541):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
W/System.err(11541): java.lang.SecurityException: getSubscriberId
W/System.err(11541):    at android.os.Parcel.createException(Parcel.java:1953)
W/System.err(11541):    at android.os.Parcel.readException(Parcel.java:1921)
W/System.err(11541):    at android.os.Parcel.readException(Parcel.java:1871)
W/System.err(11541):    at com.android.internal.telephony.IPhoneSubInfo$Stub$Proxy.getSubscriberIdForSubscriber(IPhoneSubInfo.java:603)
W/System.err(11541):    at android.telephony.TelephonyManager.getSubscriberId(TelephonyManager.java:2983)
W/System.err(11541):    at android.telephony.TelephonyManager.getSubscriberId(TelephonyManager.java:2966)
W/System.err(11541):    at com.tencent.smtt.utils.b.d(Unknown Source:21)
W/System.err(11541):    at com.tencent.smtt.sdk.a.b.a(Unknown Source:213)
W/System.err(11541):    at com.tencent.smtt.sdk.WebView.a(Unknown Source:116)
W/System.err(11541):    at com.tencent.smtt.sdk.WebView.onDetachedFromWindow(Unknown Source:27)
W/System.err(11541):    at android.view.View.dispatchDetachedFromWindow(View.java:18628)
W/System.err(11541):    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3831)
W/System.err(11541):    at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:5638)
W/System.err(11541):    at android.view.ViewGroup.removeAllViews(ViewGroup.java:5584)
W/System.err(11541):    at io.flutter.plugin.platform.SingleViewPresentation.detachState(SingleViewPresentation.java:155)
W/System.err(11541):    at io.flutter.plugin.platform.VirtualDisplayController.resize(VirtualDisplayController.java:83)
W/System.err(11541):    at io.flutter.plugin.platform.PlatformViewsController.resizePlatformView(PlatformViewsController.java:264)
W/System.err(11541):    at io.flutter.plugin.platform.PlatformViewsController.onMethodCall(PlatformViewsController.java:148)
W/System.err(11541):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
W/System.err(11541):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
W/System.err(11541):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
W/System.err(11541):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(11541):    at android.os.MessageQueue.next(MessageQueue.java:386)
W/System.err(11541):    at android.os.Looper.loop(Looper.java:169)
W/System.err(11541):    at android.app.ActivityThread.main(ActivityThread.java:7470)
W/System.err(11541):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(11541):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
W/System.err(11541):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
D/HiTouch_PressGestureDetector(11541): HiTouch on notch display, width corret:72
D/OpenGLRenderer(11541):   HWUI Binary is  enabled
D/OpenGLRenderer(11541): disableOutlineDraw is true
W/System.err(11541): javax.crypto.IllegalBlockSizeException: last block incomplete in decryption
W/System.err(11541):    at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:1174)W/System.err(11541):    at javax.crypto.Cipher.doFinal(Cipher.java:2055)
W/System.err(11541):    at com.tencent.smtt.utils.o.c(Unknown Source:31)
W/System.err(11541):    at com.tencent.smtt.sdk.a.b.b(Unknown Source:83)
W/System.err(11541):    at com.tencent.smtt.sdk.a.b.a(Unknown Source:0)
W/System.err(11541):    at com.tencent.smtt.sdk.a.c.run(Unknown Source:355)
W/System.err(11541): java.lang.NullPointerException: Attempt to get length of null array
W/System.err(11541):    at java.lang.StringFactory.newStringFromBytes(StringFactory.java:46)
W/System.err(11541):    at com.tencent.smtt.sdk.a.b.b(Unknown Source:87)
W/System.err(11541):    at com.tencent.smtt.sdk.a.b.a(Unknown Source:0)
W/System.err(11541):    at com.tencent.smtt.sdk.a.c.run(Unknown Source:355)
I/Choreographer(11541): Skipped 33 frames!  The application may be doing too much work on its main thread.
D/HiTouch_PressGestureDetector(11541): HiTouch on notch display, width corret:90
I/HiTouch_HiTouchSensor(11541): ORIENTATION_LANDSCAPE
D/HwAppInnerBoostImpl(11541): asyncReportData com.bst.bst_life_app,1,1,6,0 interval=2998
W/libEGL  (11541): EGLNativeWindowType 0xb3fd3008 disconnect failed
I/HiTouch_HiTouchSensor(11541): HiTouch restricted: Sub windows restricted.
E/Surface (11541): queueBuffer: error queuing buffer to SurfaceTexture, -19
E/ACodec  (11541): queueBuffer failed in onOutputBufferDrained: -19
E/ACodec  (11541): signalError(omxError 0x80001001, internalError -19)
E/MediaCodec(11541): Codec reported err 0xffffffed, actionCode 0, while in state 6
D/SurfaceUtils(11541): disconnecting from surface 0xb3be6808, reason disconnectFromSurface
D/mali_winsys(11541): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/HiTouch_PressGestureDetector(11541): HiTouch on notch display, height corret:99
D/OpenGLRenderer(11541):   HWUI Binary is  enabled
D/OpenGLRenderer(11541): disableOutlineDraw is true
D/AndroidRuntime(11541): Shutting down VM
E/AndroidRuntime(11541): FATAL EXCEPTION: main
E/AndroidRuntime(11541): Process: com.bst.bst_life_app, PID: 11541
E/AndroidRuntime(11541): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.DisplayAdjustments android.view.Display.getDisplayAdjustments()' on a null object reference
E/AndroidRuntime(11541):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1887)
E/AndroidRuntime(11541):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1624)
E/AndroidRuntime(11541):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7926)
E/AndroidRuntime(11541):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1079)
E/AndroidRuntime(11541):        at android.view.Choreographer.doCallbacks(Choreographer.java:885)
E/AndroidRuntime(11541):        at android.view.Choreographer.doFrame(Choreographer.java:809)
E/AndroidRuntime(11541):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1065)
E/AndroidRuntime(11541):        at android.os.Handler.handleCallback(Handler.java:891)
E/AndroidRuntime(11541):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11541):        at android.os.Looper.loop(Looper.java:207)
E/AndroidRuntime(11541):        at android.app.ActivityThread.main(ActivityThread.java:7470)
E/AndroidRuntime(11541):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11541):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AndroidRuntime(11541):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
E/CrashHandler(11541): In thread: Thread[main,5,main]
E/CrashHandler(11541): UncaughtException detected: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.DisplayAdjustments android.view.Display.getDisplayAdjustments()' on a null object reference
E/CrashHandler(11541):  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1887)
E/CrashHandler(11541):  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1624)
E/CrashHandler(11541):  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7926)
E/CrashHandler(11541):  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1079)
E/CrashHandler(11541):  at android.view.Choreographer.doCallbacks(Choreographer.java:885)
E/CrashHandler(11541):  at android.view.Choreographer.doFrame(Choreographer.java:809)
E/CrashHandler(11541):  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1065)
E/CrashHandler(11541):  at android.os.Handler.handleCallback(Handler.java:891)
E/CrashHandler(11541):  at android.os.Handler.dispatchMessage(Handler.java:102)
E/CrashHandler(11541):  at android.os.Looper.loop(Looper.java:207)
E/CrashHandler(11541):  at android.app.ActivityThread.main(ActivityThread.java:7470)
E/CrashHandler(11541):  at java.lang.reflect.Method.invoke(Native Method)
E/CrashHandler(11541):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/CrashHandler(11541):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
I/crash_recorder(11541): recordTbsCrash:
I/crash_recorder(11541):  {java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.DisplayAdjustments android.view.Display.getDisplayAdjustments()' on a null object reference
I/crash_recorder(11541):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1887)
I/crash_recorder(11541):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1624)
I/crash_recorder(11541):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7926)
I/crash_recorder(11541):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1079)
I/crash_recorder(11541):        at android.view.Choreographer.doCallbacks(Choreographer.java:885)
I/crash_recorder(11541):        at android.view.Choreographer.doFrame(Choreographer.java:809)
I/crash_recorder(11541):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1065)
I/crash_recorder(11541):        at android.os.Handler.handleCallback(Handler.java:891)
I/crash_recorder(11541):        at android.os.Handler.dispatchMessage(Handler.java:102)
I/crash_recorder(11541):        at android.os.Looper.loop(Looper.java:207)
I/crash_recorder(11541):        at android.app.ActivityThread.main(ActivityThread.java:7470)
I/crash_recorder(11541):        at java.lang.reflect.Method.invoke(Native Method)
I/crash_recorder(11541):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller
I/crash_recorder(11541): isInTbsContext, webviewType: unknown, isLoading: 0
I/Process (11541): Sending signal. PID: 11541 SIG: 9

**Comment by jerry90** [comment]
一样的问题  视频全部不对

**Comment by jerry90** [comment]
网页里面有视频 全屏时不正确

**Comment by VenusCao** [comment]
更新到最新版本试试，如果还有问题请继续回复
